# -*- coding: utf-8 -*-
"""get_region_state_name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldf2gVkSz1mAwV2c2dd2XhgfpMzkCzmb
"""

# Import the pandas library
import pandas as pd

# Import the numpy library
import numpy as np

# Import the geopy library
import geopy

# Import the glob module
import glob

# Define a function that takes latitude and longitude as parameters and returns the region name
def get_region_name(lat, lon):
  # Create a geopy Nominatim object without a timeout parameter
  geolocator = geopy.Nominatim(user_agent="Bing")
  # Use the reverse method to get the location information from the coordinates
  location = geolocator.reverse((lat, lon))
  # Get the region name from the location.raw dictionary
  region_name = location.raw["address"]["region"]
  # Return the region name
  return region_name

# Define a function that takes latitude and longitude as parameters and returns the state name
def get_state_name(lat, lon):
  # Create a geopy Nominatim object without a timeout parameter
  geolocator = geopy.Nominatim(user_agent="Bing")
  # Use the reverse method to get the location information from the coordinates
  location = geolocator.reverse((lat, lon))
  # Get the state name from the location.raw dictionary
  state_name = location.raw["address"]["state"]
  # Return the state name
  return state_name